name: Destroy scalingo application on feature/* branch deletion

on:
  delete:
    branches:
      - feature/*
  workflow_dispatch:

env:
  application-name: 'romain-cambonie-test'

jobs:
  dynamic-variables:
    outputs:
      application-name-with-ref: ${{ steps.application-name.outputs.value }}
    runs-on: ubuntu-latest
    steps:
      - name: Application name from env variable
        id: application-name
        run: |
          APPLICATION_NAME=${{ format('{0}-{1}', env.application-name, needs.get-deleted-branch-ref.outputs.deleted-branch-ref) }}
          echo "::set-output name=value::$APPLICATION_NAME"

  get-deleted-branch-ref:
    runs-on: ubuntu-latest
    outputs:
      deleted-branch-ref: ${{ steps.deleted-branch-ref.outputs.branch-ref }}
    steps:
      - name: Get the deleted branch reference without the 'feature/' prefix
        id: deleted-branch-ref
        run: echo "::set-output name=branch-ref::$(echo ${{ github.event.ref }} | cut -d'/' -f 2)"

  destroy-deployed-application:
    needs:
      - dynamic-variables
      - get-deleted-branch-ref
    uses: ./.github/workflows/_destroy-application.scalingo.reusable.yml
    with:
      application-alias: ${{ needs.dynamic-variables.outputs.application-name-with-ref }}
    secrets:
      SCALINGO_API_TOKEN: ${{ secrets.SCALINGO_API_TOKEN }}
