name: CD-Feature/Fix on scalingo
# This assume you have the following scripts in the package.json
#build
#test (used in the reusable Validation Workflow)
#lint (used in the reusable Validation Workflow)

on:
  workflow_dispatch:
#  push:
#    branches:
#      - feature/*

env:
  application-name: 'romain-cambonie-test'
  node-version: '16.15.0'
  # More details available in the docs/scalingo/addon-postgresql.md file.
  addon-plan-postgresql: 'postgresql-sandbox'

jobs:
  dynamic-variables:
    outputs:
      node-version: ${{ steps.node-version.outputs.value }}
      application-name: ${{ steps.application-name.outputs.value }}
      application-environment-slug: ${{ steps.application-environment-slug.outputs.value }}
      deployment-owner-type: ${{ steps.deployment-owner-type.outputs.value }}
      is-mattermost-hooked: ${{ steps.is-mattermost-hooked.outputs.value }}
      is-discord-hooked: ${{ steps.is-discord-hooked.outputs.value }}
    runs-on: ubuntu-latest
    steps:
      - name: Node version from env variable
        id: node-version
        run: |
          NODE_VERSION=${{ env.node-version }}
          echo "::set-output name=value::$NODE_VERSION"

      - name: Deployed application base name
        id: application-name
        run: |
          APPLICATION_NAME=${{ env.application-name }}
          echo "::set-output name=value::$APPLICATION_NAME"

      - name: Deployed application environment slug
        id: application-environment-slug
        run: |
          BRANCH_SHORT_REF=$(echo ${{ github.event.ref }} | cut -d'/' -f 4)
          echo "::set-output name=value::$BRANCH_SHORT_REF"

#      - name: Deployement Owner type ('personal' | 'organisation')
#        id: deployment-owner-type
#        run: |
#          TYPE=${{ secrets.CLEVER_ORG_ID != '' && 'organisation' || 'personal' }}
#          echo "::set-output name=value::$TYPE"

      - name: Has a mattermost webhook for notification been defined
        id: is-mattermost-hooked
        run: |
          IS_HOOKED=${{ secrets.MATTERMOST_NOTIFY_HOOK_URL != '' }}
          echo "::set-output name=value::$IS_HOOKED"

      - name: Has a discord webhook for notification been defined
        id: is-discord-hooked
        run: |
          IS_HOOKED=${{ secrets.DISCORD_NOTIFY_HOOK_URL != '' }}
          echo "::set-output name=value::$IS_HOOKED"


  dependencies:
    needs:
      - dynamic-variables
    uses: ./.github/workflows/_dependencies.reusable.yml
    with:
      node-version: ${{ needs.dynamic-variables.outputs.node-version }}

  build:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve the branch files
        uses: actions/checkout@v3

      - name: Retrieve dependencies
        uses: actions/cache@v3
        with:
          key: node_modules-${{ hashFiles('yarn.lock') }}
          path: node_modules

      - name: Build
        run: yarn build

  validation:
    needs: dependencies
    uses: ./.github/workflows/_validation.reusable.yml

  deploy:
    needs:
      - dynamic-variables
      - build
      - validation
    uses: ./.github/workflows/_deploy-application.scalingo.reusable.yml
    with:
      application-base-name: ${{ needs.dynamic-variables.outputs.application-name }}
      application-enviroment-name: ${{ needs.dynamic-variables.outputs.application-environment-slug }}
      scalingo-remote-domain-url: 'git@ssh.osc-fr1.scalingo.com'
      scalingo-ssh-host-domain: 'ssh.osc-fr1.scalingo.com'
#     deployment-owner-type: ${{ needs.dynamic-variables.outputs.deployment-owner-type }}
    secrets:
      SCALINGO_API_TOKEN: ${{ secrets.SCALINGO_API_TOKEN }}

  services:
    needs:
      - deploy
    uses: ./.github/workflows/_deploy-application.scalingo.reusable.yml
    with:
      application-base-name: ${{ needs.dynamic-variables.outputs.application-name }}
      application-enviroment-name: ${{ needs.dynamic-variables.outputs.application-environment-slug }}
      addons-plan-postgresql: ${{ env.application-name }}

  notify-mattermost:
    if: ${{ needs.dynamic-variables.outputs.is-mattermost-hooked == 'true' }}
    needs:
      - dynamic-variables
      - deploy
    uses: ./.github/workflows/_notify-deployment.mattermost.reusable.yml
    with:
      application-full-name: ${{ needs.dynamic-variables.outputs.application-environment-slug }}
      deployed-domain: ${{ needs.deploy.outputs.deployed-domain }}
    secrets:
      MATTERMOST_NOTIFY_HOOK_URL: ${{ secrets.MATTERMOST_NOTIFY_HOOK_URL }}

  notify-discord:
    if: ${{ needs.dynamic-variables.outputs.is-discord-hooked == 'true' }}
    needs:
      - dynamic-variables
      - deploy
    uses: ./.github/workflows/_notify-deployment.discord.reusable.yml
    with:
      application-full-name: ${{ needs.dynamic-variables.outputs.application-environment-slug }}
      deployed-domain: ${{ needs.deploy.outputs.deployed-domain }}
    secrets:
      DISCORD_NOTIFY_HOOK_URL: ${{ secrets.DISCORD_NOTIFY_HOOK_URL }}
